-- MySQL Script generated by MySQL Workbench
-- Thu May  1 16:41:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema taw
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `taw` ;

-- -----------------------------------------------------
-- Schema taw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taw` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `taw` ;

-- -----------------------------------------------------
-- Table `taw`.`actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taw`.`actor` ;

CREATE TABLE IF NOT EXISTS `taw`.`actor` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL DEFAULT NULL,
  `Edad` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taw`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taw`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `taw`.`tipo_usuario` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taw`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taw`.`usuario` ;

CREATE TABLE IF NOT EXISTS `taw`.`usuario` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL DEFAULT NULL,
  `Correo` VARCHAR(100) NULL DEFAULT NULL,
  `Contrasena_Hash` VARCHAR(255) NULL DEFAULT NULL,
  `Tipo_Usuario_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_usuario_tipo_usuario1_idx` (`Tipo_Usuario_ID` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_usuario1`
    FOREIGN KEY (`Tipo_Usuario_ID`)
    REFERENCES `taw`.`tipo_usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taw`.`pelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taw`.`pelicula` ;

CREATE TABLE IF NOT EXISTS `taw`.`pelicula` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(100) NULL DEFAULT NULL,
  `Fecha_Estreno` DATE NULL DEFAULT NULL,
  `Sinopsis` TEXT NULL DEFAULT NULL,
  `Presupuesto` INT NULL DEFAULT NULL,
  `Ingresos` INT NULL DEFAULT NULL,
  `Rating` DOUBLE NULL DEFAULT NULL,
  `Duracion` INT NULL DEFAULT NULL,
  `Usuario_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Usuario_ID` (`Usuario_ID` ASC) VISIBLE,
  CONSTRAINT `fk_pelicula_usuario`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `taw`.`usuario` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taw`.`casting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taw`.`casting` ;

CREATE TABLE IF NOT EXISTS `taw`.`casting` (
  `Personaje` VARCHAR(100) NULL DEFAULT NULL,
  `Pelicula_ID` INT NOT NULL,
  `Actor_ID` INT NOT NULL,
  PRIMARY KEY (`Pelicula_ID`, `Actor_ID`),
  INDEX `Actor_ID` (`Actor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_casting_actor`
    FOREIGN KEY (`Actor_ID`)
    REFERENCES `taw`.`actor` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_casting_pelicula`
    FOREIGN KEY (`Pelicula_ID`)
    REFERENCES `taw`.`pelicula` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taw`.`genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taw`.`genero` ;

CREATE TABLE IF NOT EXISTS `taw`.`genero` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taw`.`genero_pelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taw`.`genero_pelicula` ;

CREATE TABLE IF NOT EXISTS `taw`.`genero_pelicula` (
  `Pelicula_ID` INT NOT NULL,
  `Genero_ID` INT NOT NULL,
  PRIMARY KEY (`Pelicula_ID`, `Genero_ID`),
  INDEX `Genero_ID` (`Genero_ID` ASC) VISIBLE,
  CONSTRAINT `fk_genero_pelicula_genero`
    FOREIGN KEY (`Genero_ID`)
    REFERENCES `taw`.`genero` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_genero_pelicula_pelicula`
    FOREIGN KEY (`Pelicula_ID`)
    REFERENCES `taw`.`pelicula` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taw`.`lista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taw`.`lista` ;

CREATE TABLE IF NOT EXISTS `taw`.`lista` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL DEFAULT NULL,
  `Descripcion` TEXT NULL DEFAULT NULL,
  `Fecha_Creacion` DATE NULL DEFAULT NULL,
  `Usuario_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Usuario_ID` (`Usuario_ID` ASC) VISIBLE,
  CONSTRAINT `lista_ibfk_1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `taw`.`usuario` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taw`.`lista_pelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taw`.`lista_pelicula` ;

CREATE TABLE IF NOT EXISTS `taw`.`lista_pelicula` (
  `Lista_ID` INT NOT NULL,
  `Pelicula_ID` INT NOT NULL,
  `Fecha_Agregada` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Lista_ID`, `Pelicula_ID`),
  INDEX `Pelicula_ID` (`Pelicula_ID` ASC) VISIBLE,
  CONSTRAINT `lista_pelicula_ibfk_1`
    FOREIGN KEY (`Lista_ID`)
    REFERENCES `taw`.`lista` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `lista_pelicula_ibfk_2`
    FOREIGN KEY (`Pelicula_ID`)
    REFERENCES `taw`.`pelicula` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taw`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taw`.`review` ;

CREATE TABLE IF NOT EXISTS `taw`.`review` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Califica` DOUBLE NULL DEFAULT NULL,
  `Comentario` VARCHAR(500) NULL DEFAULT NULL,
  `Fecha` DATE NULL DEFAULT NULL,
  `Usuario_ID` INT NOT NULL,
  `Pelicula_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Usuario_ID` (`Usuario_ID` ASC) VISIBLE,
  INDEX `Pelicula_ID` (`Pelicula_ID` ASC) VISIBLE,
  CONSTRAINT `fk_review_pelicula`
    FOREIGN KEY (`Pelicula_ID`)
    REFERENCES `taw`.`pelicula` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_review_usuario`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `taw`.`usuario` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taw`.`trabajador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taw`.`trabajador` ;

CREATE TABLE IF NOT EXISTS `taw`.`trabajador` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL DEFAULT NULL,
  `Puesto` VARCHAR(50) NULL DEFAULT NULL,
  `Departamento` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taw`.`trabajador_pelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taw`.`trabajador_pelicula` ;

CREATE TABLE IF NOT EXISTS `taw`.`trabajador_pelicula` (
  `Tipo_Trabajo` VARCHAR(50) NULL DEFAULT NULL,
  `Trabajador_ID` INT NOT NULL,
  `Pelicula_ID` INT NOT NULL,
  PRIMARY KEY (`Trabajador_ID`, `Pelicula_ID`),
  INDEX `Pelicula_ID` (`Pelicula_ID` ASC) VISIBLE,
  CONSTRAINT `fk_trabajador_pelicula_pelicula`
    FOREIGN KEY (`Pelicula_ID`)
    REFERENCES `taw`.`pelicula` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_trabajador_pelicula_trabajador`
    FOREIGN KEY (`Trabajador_ID`)
    REFERENCES `taw`.`trabajador` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `taw`.`tipo_usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `taw`;
INSERT INTO `taw`.`tipo_usuario` (`ID`, `Tipo`) VALUES (1, 'Admin');
INSERT INTO `taw`.`tipo_usuario` (`ID`, `Tipo`) VALUES (2, 'Usuario');

COMMIT;


-- -----------------------------------------------------
-- Data for table `taw`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `taw`;
INSERT INTO `taw`.`usuario` (`ID`, `Nombre`, `Correo`, `Contrasena_Hash`, `Tipo_Usuario_ID`) VALUES (1, 'David', 'admin@gmail.com', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 1);

COMMIT;

